line-length = 120
indent-width = 4
preview = true

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
extend-select = [
  "E101",
  #"E111",
  "E501",
  "E713",
  "E4", 
  "E7", 
  "E9", 
  "F",
  "F811",
  "W291",
  "PLR0911", # inconsistent-return-statements
  "PLW0602", # redefined-builtin
  "PLW0604", # reimported
  "PLW0108", # unnecessary-pass
  "PLW0127", # assignment-from-no-return
  "PLW0129", # assert-on-tuple
  "PLW1501", # logging-not-lazy
  "PLR0124", # redefined-in-handler
  "PLR0202", # no-value-for-parameter
  "PLR0203", # no-member
  "PLR0402", # import-star-module-level
  "PLR0913", # too-many-arguments (close match to "arguments-differ")

  # Style / cleanup rules (flake8-bugbear, pyupgrade, etc.):
  "B028", # no explicit f-string required
  "B905", # consider-using-with
  "C402", # consider-using-dict-comprehension
  "C403", # consider-using-set-comprehension
  "UP032", # consider-using-f-string
  "UP037", # super-with-arguments
  "UP025", # old-ne-operator
  "UP036", # old-octal-literal
  "UP034", # old-raise-syntax
  "UP033", # print-statement
  "UP031", # backtick repr
  "UP004", # useless-object-inheritance
]
ignore = ["E731"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
line-ending = "lf"
